@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6560c1c4008d6dce4642e78f",
  "postId": "65621add107a9e52373c8abe",
  "comment": "This is my first comment",
  "profilePicture": "https://res.cloudinary.com/dfapum2fd/image/cloud/v1700209539/655723804166a7b0dd61b941"
}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/655bb41752360c08629d0be7
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/655bb41752360c08629d0be7/655e5be9b61eb699ebbdcd51
Content-Type: application/json
Accept: application/json
withCredentials: true
